version: '3.6'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.106.3
    networks:
      - adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"
      #- "68:68/tcp"
      #- "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000/tcp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    restart: unless-stopped
    volumes:
      - adguardhome-conf:/opt/adguardhome/conf
      - adguardhome-work:/opt/adguardhome/work
networks:
  adguardhome:
    name: adguardhome
volumes:
  adguardhome-conf:
    name: adguardhome-conf
  adguardhome-work:
    name: adguardhome-work
